### ISSUE TITLE
Getting error "failed to convert to plugin DTO: could not find dist/plugin.json or plugin.json " when installing the plugin

### ISSUE THREAD

**Issue by douglas-wiliam** [tinybirdco/grafana-tinybird-datasource#17]
The errors below occurred when I updated from 2.0.1 to 2.0.2 version:

Please, if someone can help me.

 I see that this version 2.0.2 correct the use of time variable in alert so in moment I can't use this feature because I can't install the plugin.

I'm running Grafana 10.0.3 in Docker
Ubuntu 22.04.2 LTS

```
Error: ✗ failed to convert to plugin DTO: could not find dist/plugin.json or plugin.json for tinybird-tinybird-datasource in /var/lib/grafana/plugins/tinybird-tinybird-datasource
Error: ✗ failed to convert to plugin DTO: could not find dist/plugin.json or plugin.json for tinybird-tinybird-datasource in /var/lib/grafana/plugins/tinybird-tinybird-datasource
Error: ✗ failed to convert to plugin DTO: could not find dist/plugin.json or plugin.json for tinybird-tinybird-datasource in /var/lib/grafana/plugins/tinybird-tinybird-datasource
Error: ✗ failed to convert to plugin DTO: could not find dist/plugin.json or plugin.json for tinybird-tinybird-datasource in /var/lib/grafana/plugins/tinybird-tinybird-datasource
Error: ✗ failed to convert to plugin DTO: could not find dist/plugin.json or plugin.json for tinybird-tinybird-datasource in /var/lib/grafana/plugins/tinybird-tinybird-datasource
Error: ✗ failed to convert to plugin DTO: could not find dist/plugin.json or plugin.json for tinybird-tinybird-datasource in /var/lib/grafana/plugins/tinybird-tinybird-datasource

```

**Comment by sdairs** [comment]
Thanks for the report @douglas-wiliam - nothing is immediately jumping to mind, so I'll need to look into it and get back to you 

cc @radchukd

**Comment by sdairs** [comment]
@douglas-wiliam  Could you share how you installed the new version, and what the contents of your `/var/lib/grafana/plugins/tinybird-tinybird-datasource` looks like?

**Comment by douglas-wiliam** [comment]
This

![image](https://github.com/tinybirdco/grafana-tinybird-datasource/assets/15745517/2467b8c5-f63a-49b4-8d6c-5b471222ffb9)

Here is my docker file:

```yaml
version: '3.8'
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    user: '0'
    environment:
      - GF_INSTALL_PLUGINS=https://github.com/tinybirdco/grafana-tinybird-datasource/releases/download/2.0.1/tinybird-tinybird-datasource-2.0.1.zip;tinybird-tinybird-datasource
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=tinybird-tinybird-datasource
      - GF_SERVER_PROTOCOL=https
      - GF_SERVER_CERT_FILE=/etc/grafana/grafana.crt
      - GF_SERVER_CERT_KEY=/etc/grafana/grafana.key

    ports:
      - '443:3000'

    volumes:
      - './data:/var/lib/grafana'
      - './certs/grafana.crt:/etc/grafana/grafana.crt'
      - './certs/grafana.key:/etc/grafana/grafana.key'

```

**Comment by douglas-wiliam** [comment]
> @douglas-wiliam Could you share how you installed the new version, and what the contents of your `/var/lib/grafana/plugins/tinybird-tinybird-datasource` looks like?

@sdairs, there is only the file `logo.svg`:

![image](https://github.com/tinybirdco/grafana-tinybird-datasource/assets/15745517/0564d1b0-e70a-48f7-bdff-fb1662b30dd5)

Here is my docker-compose file:

```yaml
version: '3.8'
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    user: '0'
    environment:
      - GF_INSTALL_PLUGINS=https://github.com/tinybirdco/grafana-tinybird-datasource/releases/download/2.0.2/tinybird-tinybird-datasource-2.0.2.zip;tinybird-tinybird-datasource
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=tinybird-tinybird-datasource
      - GF_SERVER_PROTOCOL=https
      - GF_SERVER_CERT_FILE=/etc/grafana/grafana.crt
      - GF_SERVER_CERT_KEY=/etc/grafana/grafana.key

    ports:
      - '443:3000'

    volumes:
      - './data:/var/lib/grafana'
      - './certs/grafana.crt:/etc/grafana/grafana.crt'
      - './certs/grafana.key:/etc/grafana/grafana.key'

```
Even in a non-docker instalation I had same error and the same file in the location you've pointed out.

**Comment by douglas-wiliam** [comment]
Even when I put the files in this folder before the installation, when this plugin version runs all is erased and only this `logo.svg` file remains.

**Comment by sdairs** [comment]
@douglas-wiliam I'm not too familiar with the install via Docker, but I can't replicate this in a non-docker environment - I think something is interfering with your extraction from the zip, as your plugin directory is empty. Could it be something going wrong with the docker volume mounts?

**Comment by douglas-wiliam** [comment]
@sdairs even in a non docker environment using the comand below like in documentantion I get the same error.

```
grafana cli --pluginsDir /var/lib/grafana/plugins --insecure --pluginUrl https://github.com/tinybirdco/grafana-tinybird-datasource/releases/download/2.0.2/tinybird-tinybird-datasource-2.0.2.zip plugins install tinybird-tinybird-datasource
```

It was my first try using Ubuntu 22.04.2 and after that I tried using docker that was I posted initially here and after I needed to return to 2.0.1 version of plugin that works fine in Ubuntu and Docker.

The specs in non-docker environment Grafana 10.0.3 in
Ubuntu 22.04.2 LTS

**Comment by sdairs** [comment]
@douglas-wiliam I have re-uploaded the release zip, same url - can you try again? https://github.com/tinybirdco/grafana-tinybird-datasource/releases/download/2.0.2/tinybird-tinybird-datasource-2.0.2.zip

**Comment by douglas-wiliam** [comment]
@sdairs thank you, it worked! Only thing that happen now is that the logo is missing:

![image](https://github.com/tinybirdco/grafana-tinybird-datasource/assets/15745517/383337de-a1c2-4b49-8b0d-7b45df456b31)

![image](https://github.com/tinybirdco/grafana-tinybird-datasource/assets/15745517/bb963582-2426-4d67-8585-b46e23a4b208)

**Comment by sdairs** [comment]
Great - looks like we made a mistake in the release zip - glad its working now! I'll get the logo fixed shortly too!

**Comment by douglas-wiliam** [comment]
Okay @sdairs  so can I close this ISSUE?

**Comment by sdairs** [comment]
Sure, let's close it :) I'll bump when the logo is fixed
